import { n as getScoreLabel, t as calculateScore } from "./score-C2C2ephU.js";
import {
  A as ReactDoctorRunnerUnavailableError,
  C as ReactDoctorError,
  D as ReactDoctorProjectError,
  E as ReactDoctorPackageJsonNotFoundError,
  M as ReactDoctorUnsupportedRuntimeError,
  N as isReactDoctorError,
  O as ReactDoctorProjectNotFoundError,
  P as toReactDoctorErrorInfo,
  S as ReactDoctorConfigNotFoundError,
  T as ReactDoctorNoReactDependencyError,
  _ as ReactDoctorCancelledError,
  a as DEPENDENCIES_RULE_ID,
  b as ReactDoctorCheckSkippedError,
  c as reactProjectStructureRule,
  d as defineRule,
  g as ReactDoctorAmbiguousProjectError,
  i as REACT_ARCHITECTURE_RULE_ID,
  j as ReactDoctorTimeoutError,
  k as ReactDoctorReportError,
  l as reactDoctorOxlintPlugin,
  n as createRuleRegistry,
  o as DEAD_CODE_RULE_ID,
  r as ruleRegistry,
  t as coreRules,
  v as ReactDoctorCheckError,
  w as ReactDoctorInvalidConfigError,
  x as ReactDoctorConfigError,
  y as ReactDoctorCheckFailedError,
} from "./rules-k6al64g-.js";
import {
  a as runOxlint,
  c as parseReactMajorVersion,
  d as calculateReactDoctorScore,
  f as summarizeReactDoctorResult,
  h as resolveConfigRootDirectory,
  i as OXLINT_CHECK_ID,
  l as toOxlintProjectInfo,
  m as loadReactDoctorConfig,
  n as diagnose,
  o as filterReactDoctorIssues,
  p as clearReactDoctorConfigCache,
  r as inspectReactProjectCore,
  s as discoverReactProject,
  t as clearCaches,
  u as buildReactDoctorJsonReport,
} from "./compat-CAnuRQqf.js";
import {
  _ as createReactDoctorOxlintConfig,
  a as BUILTIN_A11Y_OXLINT_RULES,
  b as shouldEnableReactDoctorOxlintRule,
  c as CURATED_OXLINT_RULES,
  d as REACT_COMPILER_OXLINT_RULES,
  f as REACT_DOCTOR_CUSTOM_OXLINT_RULES,
  g as buildReactDoctorOxlintCapabilities,
  h as TANSTACK_START_OXLINT_RULES,
  i as ALL_REACT_DOCTOR_OXLINT_RULE_KEYS,
  l as GLOBAL_REACT_DOCTOR_OXLINT_RULES,
  m as TANSTACK_QUERY_OXLINT_RULES,
  n as REACT_DOCTOR_OXLINT_RULE_ID_PREFIX,
  o as BUILTIN_OXLINT_RULES,
  p as REACT_NATIVE_OXLINT_RULES,
  r as reactDoctorOxlintRuleMetadata,
  s as BUILTIN_REACT_OXLINT_RULES,
  t as REACT_DOCTOR_OXLINT_PLUGIN_NAMESPACE,
  u as NEXTJS_OXLINT_RULES,
  y as reactPeerRangeMinMajor,
} from "./metadata-pW35UeI4.js";
import reactDoctorEslintPlugin from "./eslint-plugin.js";
//#region src/sdk/create-react-doctor.ts
const mergeInspectOptions = (defaults, options) => ({
  ...defaults,
  ...options,
  rootDirectory: options.rootDirectory ?? defaults.rootDirectory,
});
const createReactDoctor = (options = {}) => ({
  inspect: (runOptions = {}) => inspectReactProjectCore(mergeInspectOptions(options, runOptions)),
});
const inspectReactProject = (options = {}) => createReactDoctor(options).inspect();
//#endregion
export {
  ALL_REACT_DOCTOR_OXLINT_RULE_KEYS,
  BUILTIN_A11Y_OXLINT_RULES,
  BUILTIN_OXLINT_RULES,
  BUILTIN_REACT_OXLINT_RULES,
  CURATED_OXLINT_RULES,
  DEAD_CODE_RULE_ID,
  DEPENDENCIES_RULE_ID,
  GLOBAL_REACT_DOCTOR_OXLINT_RULES,
  NEXTJS_OXLINT_RULES,
  OXLINT_CHECK_ID,
  REACT_ARCHITECTURE_RULE_ID,
  REACT_COMPILER_OXLINT_RULES,
  REACT_DOCTOR_CUSTOM_OXLINT_RULES,
  REACT_DOCTOR_OXLINT_PLUGIN_NAMESPACE,
  REACT_DOCTOR_OXLINT_RULE_ID_PREFIX,
  REACT_NATIVE_OXLINT_RULES,
  ReactDoctorAmbiguousProjectError,
  ReactDoctorCancelledError,
  ReactDoctorCheckError,
  ReactDoctorCheckFailedError,
  ReactDoctorCheckSkippedError,
  ReactDoctorConfigError,
  ReactDoctorConfigNotFoundError,
  ReactDoctorError,
  ReactDoctorInvalidConfigError,
  ReactDoctorNoReactDependencyError,
  ReactDoctorPackageJsonNotFoundError,
  ReactDoctorProjectError,
  ReactDoctorProjectNotFoundError,
  ReactDoctorReportError,
  ReactDoctorRunnerUnavailableError,
  ReactDoctorTimeoutError,
  ReactDoctorUnsupportedRuntimeError,
  TANSTACK_QUERY_OXLINT_RULES,
  TANSTACK_START_OXLINT_RULES,
  buildReactDoctorJsonReport,
  buildReactDoctorOxlintCapabilities,
  calculateReactDoctorScore,
  calculateScore,
  clearCaches,
  clearReactDoctorConfigCache,
  coreRules,
  createReactDoctor,
  createReactDoctorOxlintConfig,
  createRuleRegistry,
  defineRule,
  diagnose,
  discoverReactProject,
  filterReactDoctorIssues,
  getScoreLabel,
  inspectReactProject,
  isReactDoctorError,
  loadReactDoctorConfig,
  parseReactMajorVersion,
  reactDoctorEslintPlugin,
  reactDoctorOxlintPlugin,
  reactDoctorOxlintRuleMetadata,
  reactPeerRangeMinMajor,
  reactProjectStructureRule,
  resolveConfigRootDirectory,
  ruleRegistry,
  runOxlint,
  shouldEnableReactDoctorOxlintRule,
  summarizeReactDoctorResult,
  toOxlintProjectInfo,
  toReactDoctorErrorInfo,
};

//# sourceMappingURL=sdk.js.map
