const PLUGIN_CATEGORY_MAP: Record<string, string> = {
  effect: "State & Effects",
  eslint: "Correctness",
  import: "Bundle Size",
  jest: "Correctness",
  "jsx-a11y": "Accessibility",
  knip: "Dead Code",
  n: "Correctness",
  nextjs: "Next.js",
  node: "Correctness",
  oxc: "Correctness",
  promise: "Correctness",
  react: "Correctness",
  "react-doctor": "Other",
  "react-hooks": "Correctness",
  "react-hooks-js": "React Compiler",
  typescript: "Correctness",
  unicorn: "Correctness",
  vitest: "Correctness",
};

const RULE_CATEGORY_MAP: Record<string, string> = {
  "react-doctor/advanced-event-handler-refs": "Performance",
  "react-doctor/advanced-init-once": "Performance",
  "react-doctor/advanced-use-latest": "Performance",
  "react-doctor/async-api-routes": "Performance",
  "react-doctor/async-await-in-loop": "Performance",
  "react-doctor/async-cheap-condition-before-await": "Performance",
  "react-doctor/async-defer-await": "Performance",
  "react-doctor/async-dependencies": "Performance",
  "react-doctor/async-parallel": "Performance",
  "react-doctor/async-suspense-boundaries": "Performance",
  "react-doctor/bundle-conditional": "Bundle Size",
  "react-doctor/bundle-preload": "Bundle Size",
  "react-doctor/client-event-listeners": "Performance",
  "react-doctor/client-localstorage-no-version": "Correctness",
  "react-doctor/client-passive-event-listeners": "Performance",
  "react-doctor/client-swr-dedup": "Performance",
  "react-doctor/design-no-bold-heading": "Architecture",
  "react-doctor/design-no-three-period-ellipsis": "Architecture",
  "react-doctor/design-no-vague-button-label": "Accessibility",
  "react-doctor/effect-needs-cleanup": "State & Effects",
  "react-doctor/effect-no-adjust-state-on-prop-change": "State & Effects",
  "react-doctor/effect-no-chain-state-updates": "State & Effects",
  "react-doctor/effect-no-derived-state": "State & Effects",
  "react-doctor/effect-no-event-handler": "State & Effects",
  "react-doctor/effect-no-initialize-state": "State & Effects",
  "react-doctor/effect-no-pass-data-to-parent": "State & Effects",
  "react-doctor/effect-no-pass-live-state-to-parent": "State & Effects",
  "react-doctor/effect-no-reset-all-state-on-prop-change": "State & Effects",
  "react-doctor/expo-no-axios": "React Native",
  "react-doctor/i18n-no-dynamic-translation-key": "Architecture",
  "react-doctor/i18n-no-literal-jsx-text": "Architecture",
  "react-doctor/js-batch-dom-css": "Performance",
  "react-doctor/js-cache-function-results": "Performance",
  "react-doctor/js-cache-property-access": "Performance",
  "react-doctor/js-cache-storage": "Performance",
  "react-doctor/js-combine-iterations": "Performance",
  "react-doctor/js-early-exit": "Performance",
  "react-doctor/js-flatmap-filter": "Performance",
  "react-doctor/js-hoist-intl": "Performance",
  "react-doctor/js-hoist-regexp": "Performance",
  "react-doctor/js-index-maps": "Performance",
  "react-doctor/js-length-check-first": "Performance",
  "react-doctor/js-min-max-loop": "Performance",
  "react-doctor/js-request-idle-callback": "Performance",
  "react-doctor/js-set-map-lookups": "Performance",
  "react-doctor/js-tosorted-immutable": "Performance",
  "react-doctor/mobx-observer-named-component": "Correctness",
  "react-doctor/motion-no-hover-transform-on-target": "Performance",
  "react-doctor/motion-no-motion-in-lazymotion-strict": "Bundle Size",
  "react-doctor/nextjs-async-client-component": "Next.js",
  "react-doctor/nextjs-image-missing-sizes": "Next.js",
  "react-doctor/nextjs-inline-script-missing-id": "Next.js",
  "react-doctor/nextjs-missing-metadata": "Next.js",
  "react-doctor/nextjs-no-a-element": "Next.js",
  "react-doctor/nextjs-no-client-fetch-for-server-data": "Next.js",
  "react-doctor/nextjs-no-client-side-redirect": "Next.js",
  "react-doctor/nextjs-no-css-link": "Next.js",
  "react-doctor/nextjs-no-font-link": "Next.js",
  "react-doctor/nextjs-no-head-import": "Next.js",
  "react-doctor/nextjs-no-img-element": "Next.js",
  "react-doctor/nextjs-no-native-script": "Next.js",
  "react-doctor/nextjs-no-polyfill-script": "Next.js",
  "react-doctor/nextjs-no-redirect-in-try-catch": "Next.js",
  "react-doctor/nextjs-no-side-effect-in-get-handler": "Security",
  "react-doctor/nextjs-no-use-search-params-without-suspense": "Next.js",
  "react-doctor/no-aria-expanded-without-controls": "Accessibility",
  "react-doctor/no-aria-invalid-without-describedby": "Accessibility",
  "react-doctor/no-array-index-as-key": "Correctness",
  "react-doctor/no-barrel-import": "Bundle Size",
  "react-doctor/no-blocked-paste": "Accessibility",
  "react-doctor/no-button-navigation": "Accessibility",
  "react-doctor/no-cascading-set-state": "State & Effects",
  "react-doctor/no-dark-mode-glow": "Architecture",
  "react-doctor/no-default-props": "Architecture",
  "react-doctor/no-derived-state-effect": "State & Effects",
  "react-doctor/no-derived-useState": "State & Effects",
  "react-doctor/no-direct-state-mutation": "State & Effects",
  "react-doctor/no-disabled-zoom": "Accessibility",
  "react-doctor/no-document-start-view-transition": "Correctness",
  "react-doctor/no-dynamic-import-path": "Bundle Size",
  "react-doctor/no-effect-chain": "State & Effects",
  "react-doctor/no-effect-event-handler": "State & Effects",
  "react-doctor/no-effect-event-in-deps": "State & Effects",
  "react-doctor/no-eval": "Security",
  "react-doctor/no-event-trigger-state": "State & Effects",
  "react-doctor/no-fetch-in-effect": "State & Effects",
  "react-doctor/no-flush-sync": "Performance",
  "react-doctor/no-full-lodash-import": "Bundle Size",
  "react-doctor/no-generic-handler-names": "Architecture",
  "react-doctor/no-giant-component": "Architecture",
  "react-doctor/no-global-css-variable-animation": "Performance",
  "react-doctor/no-gradient-text": "Architecture",
  "react-doctor/no-gray-on-colored-background": "Accessibility",
  "react-doctor/no-icon-only-button-without-label": "Accessibility",
  "react-doctor/no-inline-bounce-easing": "Performance",
  "react-doctor/no-inline-exhaustive-style": "Architecture",
  "react-doctor/no-inline-prop-on-memo-component": "Performance",
  "react-doctor/no-justified-text": "Accessibility",
  "react-doctor/no-large-animated-blur": "Performance",
  "react-doctor/no-layout-property-animation": "Performance",
  "react-doctor/no-layout-transition-inline": "Performance",
  "react-doctor/no-legacy-class-lifecycles": "Correctness",
  "react-doctor/no-legacy-context-api": "Correctness",
  "react-doctor/no-long-transition-duration": "Performance",
  "react-doctor/no-many-boolean-props": "Architecture",
  "react-doctor/no-mirror-prop-effect": "State & Effects",
  "react-doctor/no-moment": "Bundle Size",
  "react-doctor/no-mutable-in-deps": "State & Effects",
  "react-doctor/no-nested-component-definition": "Correctness",
  "react-doctor/no-outline-none": "Accessibility",
  "react-doctor/no-permanent-will-change": "Performance",
  "react-doctor/no-polymorphic-children": "Architecture",
  "react-doctor/no-prevent-default": "Correctness",
  "react-doctor/no-prop-callback-in-effect": "State & Effects",
  "react-doctor/no-pure-black-background": "Architecture",
  "react-doctor/no-random-key": "Correctness",
  "react-doctor/no-react-dom-deprecated-apis": "Architecture",
  "react-doctor/no-react19-deprecated-apis": "Architecture",
  "react-doctor/no-render-in-render": "Architecture",
  "react-doctor/no-render-prop-children": "Architecture",
  "react-doctor/no-scale-from-zero": "Performance",
  "react-doctor/no-secrets-in-client-code": "Security",
  "react-doctor/no-set-state-in-render": "State & Effects",
  "react-doctor/no-settimeout-state-fix": "State & Effects",
  "react-doctor/no-side-tab-border": "Architecture",
  "react-doctor/no-swallowed-error": "Security",
  "react-doctor/no-tiny-text": "Accessibility",
  "react-doctor/no-transition-all": "Performance",
  "react-doctor/no-uncontrolled-input": "Correctness",
  "react-doctor/no-undeferred-third-party": "Bundle Size",
  "react-doctor/no-usememo-simple-expression": "Performance",
  "react-doctor/no-wide-letter-spacing": "Architecture",
  "react-doctor/no-z-index-9999": "Architecture",
  "react-doctor/prefer-dynamic-import": "Bundle Size",
  "react-doctor/prefer-use-effect-event": "State & Effects",
  "react-doctor/prefer-use-sync-external-store": "State & Effects",
  "react-doctor/prefer-useReducer": "State & Effects",
  "react-doctor/query-mutation-missing-invalidation": "TanStack Query",
  "react-doctor/query-no-query-in-effect": "TanStack Query",
  "react-doctor/query-no-rest-destructuring": "TanStack Query",
  "react-doctor/query-no-unstable-deps": "TanStack Query",
  "react-doctor/query-no-unstable-query-key": "TanStack Query",
  "react-doctor/query-no-usequery-for-mutation": "TanStack Query",
  "react-doctor/query-no-void-query-fn": "TanStack Query",
  "react-doctor/query-stable-query-client": "TanStack Query",
  "react-doctor/r3f-no-clone-in-frame": "Performance",
  "react-doctor/r3f-no-new-in-frame": "Performance",
  "react-doctor/r3f-no-set-state-in-frame": "Performance",
  "react-doctor/radix-aschild-single-child": "Correctness",
  "react-doctor/react-compiler-destructure-method": "Architecture",
  "react-doctor/rendering-activity": "Performance",
  "react-doctor/rendering-animate-svg-wrapper": "Performance",
  "react-doctor/rendering-conditional-render": "Correctness",
  "react-doctor/rendering-content-visibility": "Performance",
  "react-doctor/rendering-hoist-jsx": "Performance",
  "react-doctor/rendering-hydration-mismatch-time": "Correctness",
  "react-doctor/rendering-hydration-no-flicker": "Performance",
  "react-doctor/rendering-hydration-suppress-warning": "Correctness",
  "react-doctor/rendering-resource-hints": "Performance",
  "react-doctor/rendering-script-defer-async": "Performance",
  "react-doctor/rendering-svg-precision": "Performance",
  "react-doctor/rendering-usetransition-loading": "Performance",
  "react-doctor/rerender-defer-reads-hook": "Performance",
  "react-doctor/rerender-dependencies": "State & Effects",
  "react-doctor/rerender-derived-state-from-hook": "Performance",
  "react-doctor/rerender-functional-setstate": "Performance",
  "react-doctor/rerender-lazy-state-init": "Performance",
  "react-doctor/rerender-memo": "Performance",
  "react-doctor/rerender-memo-before-early-return": "Performance",
  "react-doctor/rerender-memo-with-default-value": "Performance",
  "react-doctor/rerender-split-combined-hooks": "Performance",
  "react-doctor/rerender-state-only-in-handlers": "Performance",
  "react-doctor/rerender-transitions-scroll": "Performance",
  "react-doctor/rerender-use-deferred-value": "Performance",
  "react-doctor/rerender-use-ref-transient-values": "Performance",
  "react-doctor/rhf-no-nested-object-setvalue": "Correctness",
  "react-doctor/rhf-no-watch-render": "Performance",
  "react-doctor/rn-animate-layout-property": "React Native",
  "react-doctor/rn-animation-reaction-as-derived": "React Native",
  "react-doctor/rn-bottom-sheet-prefer-native": "React Native",
  "react-doctor/rn-list-callback-per-row": "React Native",
  "react-doctor/rn-list-data-mapped": "React Native",
  "react-doctor/rn-list-recyclable-without-types": "React Native",
  "react-doctor/rn-no-deprecated-modules": "React Native",
  "react-doctor/rn-no-dimensions-get": "React Native",
  "react-doctor/rn-no-inline-flatlist-renderitem": "React Native",
  "react-doctor/rn-no-inline-object-in-list-item": "React Native",
  "react-doctor/rn-no-legacy-expo-packages": "React Native",
  "react-doctor/rn-no-legacy-shadow-styles": "React Native",
  "react-doctor/rn-no-non-native-navigator": "React Native",
  "react-doctor/rn-no-raw-text": "React Native",
  "react-doctor/rn-no-scroll-state": "React Native",
  "react-doctor/rn-no-scrollview-mapped-list": "React Native",
  "react-doctor/rn-no-single-element-style-array": "React Native",
  "react-doctor/rn-no-web-dom-elements": "React Native",
  "react-doctor/rn-prefer-content-inset-adjustment": "React Native",
  "react-doctor/rn-prefer-expo-image": "React Native",
  "react-doctor/rn-prefer-pressable": "React Native",
  "react-doctor/rn-prefer-reanimated": "React Native",
  "react-doctor/rn-pressable-shared-value-mutation": "React Native",
  "react-doctor/rn-scrollview-content-container-padding": "React Native",
  "react-doctor/rn-scrollview-dynamic-padding": "React Native",
  "react-doctor/rn-style-prefer-boxshadow": "React Native",
  "react-doctor/server-after-nonblocking": "Server",
  "react-doctor/server-auth-actions": "Server",
  "react-doctor/server-cache-lru": "Server",
  "react-doctor/server-cache-react": "Server",
  "react-doctor/server-cache-with-object-literal": "Server",
  "react-doctor/server-dedup-props": "Server",
  "react-doctor/server-fetch-without-revalidate": "Server",
  "react-doctor/server-hoist-static-io": "Server",
  "react-doctor/server-no-mutable-module-state": "Server",
  "react-doctor/server-parallel-fetching": "Server",
  "react-doctor/server-parallel-nested-fetching": "Server",
  "react-doctor/server-sequential-independent-await": "Server",
  "react-doctor/server-serialization": "Server",
  "react-doctor/shadcn-no-direct-radix-import": "Architecture",
  "react-doctor/storybook-await-play-interactions": "Correctness",
  "react-doctor/swr-no-empty-key": "Correctness",
  "react-doctor/swr-no-unstable-key": "Correctness",
  "react-doctor/tailwind-no-conflicting-classes": "Correctness",
  "react-doctor/tailwind-no-default-palette": "Architecture",
  "react-doctor/tailwind-no-redundant-padding-axes": "Architecture",
  "react-doctor/tailwind-no-redundant-size-axes": "Architecture",
  "react-doctor/tailwind-no-space-on-flex-children": "Architecture",
  "react-doctor/tailwind-oklch-alpha-syntax": "Correctness",
  "react-doctor/tanstack-ai-chat-lifecycle-middleware": "TanStack AI",
  "react-doctor/tanstack-ai-no-direct-client-import": "TanStack AI",
  "react-doctor/tanstack-ai-no-manual-sse-response": "TanStack AI",
  "react-doctor/tanstack-ai-no-vercel-sdk-patterns": "TanStack AI",
  "react-doctor/tanstack-ai-output-schema": "TanStack AI",
  "react-doctor/tanstack-start-get-mutation": "Security",
  "react-doctor/tanstack-start-loader-parallel-fetch": "Performance",
  "react-doctor/tanstack-start-missing-head-content": "TanStack Start",
  "react-doctor/tanstack-start-no-anchor-element": "TanStack Start",
  "react-doctor/tanstack-start-no-direct-fetch-in-loader": "TanStack Start",
  "react-doctor/tanstack-start-no-dynamic-server-fn-import": "TanStack Start",
  "react-doctor/tanstack-start-no-navigate-in-render": "TanStack Start",
  "react-doctor/tanstack-start-no-secrets-in-loader": "Security",
  "react-doctor/tanstack-start-no-use-server-in-handler": "TanStack Start",
  "react-doctor/tanstack-start-no-useeffect-fetch": "TanStack Start",
  "react-doctor/tanstack-start-redirect-in-try-catch": "TanStack Start",
  "react-doctor/tanstack-start-route-property-order": "TanStack Start",
  "react-doctor/tanstack-start-server-fn-method-order": "TanStack Start",
  "react-doctor/tanstack-start-server-fn-validate-input": "TanStack Start",
  "react-doctor/testing-await-user-event": "Correctness",
  "react-doctor/testing-no-container-query": "Correctness",
  "react-doctor/use-lazy-motion": "Bundle Size",
};

const lookupOwnString = (record: Record<string, string>, key: string): string | undefined =>
  Object.hasOwn(record, key) ? record[key] : undefined;

export const resolveOxlintDiagnosticCategory = (pluginName: string, ruleId: string): string => {
  const ruleKey = `${pluginName}/${ruleId}`;
  return (
    lookupOwnString(RULE_CATEGORY_MAP, ruleKey) ??
    lookupOwnString(PLUGIN_CATEGORY_MAP, pluginName) ??
    "Other"
  );
};
