import { defineRule } from "../../utils/define-rule.js";
import type { Rule } from "../../utils/rule.js";
import type { RuleContext } from "../../utils/rule-context.js";
import { isNodeOfType } from "../../utils/is-node-of-type.js";
import type { EsTreeNodeOfType } from "../../utils/es-tree-node-of-type.js";

const SVG_PATH_HIGH_PRECISION_PATTERN = /\d+\.\d{4,}/;

const SVG_PATH_ATTRIBUTES = new Set(["d", "points", "transform"]);

// Directory segments that conventionally host design-tool output —
// Figma / Sketch / Illustrator exports. The high-precision paths
// there come from the exporter, not the engineer; flagging them is
// unactionable noise (re-export will reintroduce the precision).
const AUTO_GENERATED_PATH_SEGMENTS: ReadonlyArray<string> = [
  "/assets/",
  "/generated/",
  "/__generated__/",
  "/figma/",
  "/sketch/",
  "/illustrator/",
  "/icons/",
  "/icon/",
  "/brand/",
  "/logo/",
  "/logos/",
  "/svg/",
  "/svgs/",
  "/emoji/",
  "/emojis/",
  "/flags/",
];

// File basenames that conventionally host curated SVG asset
// collections — exported once from a design tool (Figma / Sketch /
// Illustrator / IconJar) and then dropped in. The decimal precision
// rule's recommendation is to "truncate decimals", but anyone
// touching a regenerated icon set would just paste the new export
// and re-introduce the precision.
const ICON_ASSET_BASENAME_PATTERN =
  /^(icons?|smileys?|logos?|logomark|.*-logo|.*-lockup|country[-_]?vectors?|svg[-_]?sprite|flag[-_]?sprite|sprite|.*-icon|.*Icon)\.(t|j)sx?$/i;

const isAutoGeneratedSvgFile = (filename: string | undefined): boolean => {
  if (!filename) return false;
  for (const segment of AUTO_GENERATED_PATH_SEGMENTS) {
    if (filename.includes(segment)) return true;
  }
  const lastSlash = filename.lastIndexOf("/");
  const basename = lastSlash >= 0 ? filename.slice(lastSlash + 1) : filename;
  if (ICON_ASSET_BASENAME_PATTERN.test(basename)) return true;
  return false;
};

// HACK: SVG path strings with 4+ decimals (e.g. `M 10.293847 20.847362`)
// add bytes for sub-pixel precision the user can't see. Most editors
// emit these by default; truncating to 1–2 decimals trims 30–50% off
// markup with no visible difference.
export const renderingSvgPrecision = defineRule<Rule>({
  id: "rendering-svg-precision",
  severity: "warn",
  category: "Performance",
  recommendation:
    "Truncate path/points/transform decimals to 1–2 digits — sub-pixel precision adds bytes with no visible difference",
  create: (context: RuleContext) => {
    const isAutoGenerated = isAutoGeneratedSvgFile(context.getFilename?.());
    return {
      JSXAttribute(node: EsTreeNodeOfType<"JSXAttribute">) {
        if (isAutoGenerated) return;
        if (!isNodeOfType(node.name, "JSXIdentifier")) return;
        if (!SVG_PATH_ATTRIBUTES.has(node.name.name)) return;
        if (!isNodeOfType(node.value, "Literal")) return;
        const value = node.value.value;
        if (typeof value !== "string") return;
        if (!SVG_PATH_HIGH_PRECISION_PATTERN.test(value)) return;

        context.report({
          node,
          message: `SVG ${node.name.name} attribute uses 4+ decimal precision — truncate to 1–2 decimals to shrink markup with no visible difference`,
        });
      },
    };
  },
});
